### ISSUE TITLE
async/await with next/back

### ISSUE THREAD

**Issue by solidevolution** [xaksis/vue-good-wizard#13]
Hello,

first, thx for this draft. I missed the possibility to fetch / handle asynchron data with the wizard.
In my opinion, there are a lot of functional pitfalls so i would use this.$emit inside the wizard and let the developer handle the "go or go not to next" explicit. I tried to use your way with a complex multi step form which needs more data in some cases on later steps. I must fetch them later async from api, so i need an "stop go next" for validation and fetching data.

**Comment by xaksis** [comment]
Hi @solidevolution, I'm glad vue-good-wizard has been useful to you. The [advanced usecase](https://github.com/xaksis/vue-good-wizard#advanced-usecase---call-next-or-back-asynchronously) example goes over exactly your usecase. 

If we go the emit event route, following would be needed: 

* attach an event hander to @next-clicked
* expose an internal function goNext so users can do this.$refs.wizard.goNext
* have another property that tells the wizard that this is an async wizard... so don't automatically move to the next step. (because we don't want this overhead for a simple synchronous wizard)

The current implementation lets the developers `return false` if they're not ready to go to the next step and call `goNext(true)` whenever the async call is done. This i think is much less overhead than the above. 

I'm going to close this ticket. Let me know if the example provided doesn't solve your usecase.
